### ISSUE TITLE
Codify doesn't deal well with unknown resource types

### ISSUE THREAD

**Issue by larsks** [kris-nova/naml#105]
I tried running `naml codify` on an `ObjectBucketClaim` resource:

```
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: example-obc
spec:
  generateBucketName: example-obc
  storageClassName: openshift-storage.noobaa.io
```

I was expecting it to fail due to an unknown resource type, but to my surprise it didn't emit any errors. The resulting `main.go` has no resources (and does not compile).

It would be nice if `naml codify` would emit an error (and fail) when it is unable to successfully convert the input.
